export const data = [
    {
       id:0,
        image:"images/courses2.jpg",
        name:"Portfolio Website ",
        head:"Technologies : REACT",
        para2:"Portfolio to showcase the relvant skills that proper align one's profile.List of projects sections successfully completed. Included functionalities of Contact features with email based messaging system. User attractive and animated showcases. Mobile Responsive and Highly optimized",
        link:"https://shivayy.netlify.app/",
        time:"Completed",
    },
    { 
      id:1,
      image:"images/courses5.jpg",
      name:"IICS College Website  ",
      head:"Technologies : MERN STACK",
      para2:"Website with all college details with all types of cources and important notice regarding admission dates.Placed students sections and their testmonials.Gallery including images of college and their students. User attractive and animated showcases. Mobile Responsive and Highly optimized",
      link:"https://iicscollege.netlify.app",
      time:"Completed",
  },
  { 
    id:2,
    image:"images/courses3.jpg",
    name:" Temple Mangement Website  ",
    head:"Technologies : MERN STACK",
    para2:" This website includes features of temple visting timming.Important Anouncement regarding festivals and their celebration notice in different section.Helping methods include payment and other required items. User attractive and animated showcases. Mobile Responsive and Highly optimized",
    link:"###",
    time:"In progress",
},
{ 
    id:3,
    image:"images/courses5.jpg",
    name:"Ecommerce Website  ",
    head:"Technologies : MERN STACK",
    para2:"Searching and sorting functionality with filter options.Cart feature with real feel of payment system.Included functionalities of admin dashboard who can add and delete products.Top sellers big deals sections along with top companies .Discount features added. User attractive and animated showcases.  Mobile Responsive and Highly optimized",
    link:"###",
    time:"In progress",
},
{ 
    id:4,
    image:"images/courses1.jpg",
    name:"Car Rental Website  ",
    head:"Technologies: MERN STACK",
    para2:" Car booking features.Variety of Cars.Dummy Payment system. Included functionalities of Contact features with the owner. User attractive and animated showcases. Mobile Responsive and Highly optimized",
    link:"###",
    time:"In progress",
},
{ 
    id:5,
    image:"images/courses2.jpg",
    name:"Dating Website  ",
    head:"Technologies: MERN STACK",
    para2:" Implemended authorization and authentication features with login and logout features along with registration. Included functionalities of one to one messaging system. User attractive and animated showcases. Mobile Responsive and Highly optimized",
    link:"###",
    time:"In progress",
},
];
